### ISSUE TITLE
Ffmpeg and broken depends

### ISSUE THREAD

**Issue by paulcarroty** [FedoraUnited/packages#11]
Our repository is incompatible with browsers (Chromium) from Russian Fedora repo because were built with old `ffmpeg 2.6`. I'm just test it on my F25. 

Here's two way to fix it:

1. Switch back to `ffmpeg 2.6`.

2. Include the browsers in our repository. My tests builds is ready.

Any ideas @sergiomb2 @kuboosoft ?

**Comment by kuboosoft** [comment]
You need rebuilt the src.rpm with the current ffmpeg; sorry but rebuilt chromium is the death; my machine isn't powerfull... Maybe you can fork the copr from 'https://copr.fedorainfracloud.org/coprs/churchyard/chromium-russianfedora/' and make you a new rpm using the current ffmpeg in Fedora United

**Comment by paulcarroty** [comment]
> Maybe you can fork the copr from 'https://copr.fedorainfracloud.org/coprs/churchyard/chromium-russianfedora/'

Those builds isn't use ffmpeg, I've checked the logs. Our users should be able to play all HTML5 content.

>  my machine isn't powerfull...
My too. But Love Is All You Need ©, @kuboosoft :smile:

**Comment by paulcarroty** [comment]
@kuboosoft resolved by https://github.com/FedoraUnited/chromium https://github.com/FedoraUnited/chromium-pepper-flash
