### ISSUE TITLE
Mass rebuilds: why we don't like it

### ISSUE THREAD

**Issue by paulcarroty** [FedoraUnited/packages#12]
Note for local `daily snaphots lovers` :smile: : I think you understand that basic software and libraries like `ffmpeg, x264, x265` must stay stable so much as possible? In other side, we'll need the `compat-libx` libraries.
@kuboosoft

**Comment by kuboosoft** [comment]
Don't worry; if Fedora maintains your tree updated; our packages too.  Arch Linux works same way; gentoo; and various PPA in Ubuntu ;)
Example: I using now Opera, the current stable opera-35.0... working fine with ffmpeg 3.0.1 but need a old openssl version, yes I have my own compat openssl (works fine); also we can make compat-libs. Other example kodi 16.1 doesn't compile with the current gcc6; well I packed my  old gcc5.3 and works fine. The current issue about vlc; if we don't package the current version, vlc does not play nothing ;)
