### ISSUE TITLE
libmusicbrainz5 why we need this in Fedora united repo? 

### ISSUE THREAD

**Issue by sergiomb2** [FedoraUnited/packages#2]
https://googledrive.com/host/0ByOofIMiUfxPSG00M3hVRHVmYUE/srpm/repoview/libmusicbrainz5.html

we have libmusicbrainz5 in Fedora proper, libmusicbrainz5-5.1.0-4.fc23.src.rpm:  https://apps.fedoraproject.org/packages/libmusicbrainz5

What I am missing ?

**Comment by kuboosoft** [comment]
Maybe in our time; wasn't available in Fedora 24. Because I can't see a patch between the official package and Fedora United; check date "Feb 22 2016"

**Comment by sergiomb2** [comment]
libmusicbrainz5-5.1.0-1.fc22  	is available since 2014-11-27 09:00:42 ... you may check in koji : http://koji.fedoraproject.org/koji/packageinfo?packageID=14604

**Comment by kuboosoft** [comment]
I don't remember why I made it; remember I made it in rawhide, when did't exist a complete target for Fedora 24...

**Comment by paulcarroty** [comment]
So, @kuboosoft @sergiomb2, what's verdict? Can we use the system libmusicbrainz5?

**Comment by kuboosoft** [comment]
Maybe only for test purposes...
