### ISSUE TITLE
Mpv and GNOME-mpv

### ISSUE THREAD

**Issue by paulcarroty** [FedoraUnited/packages#3]
I think we need to add this packages, it's very powerful and usable players. @sergiomb2 @kuboosoft ?

**Comment by kuboosoft** [comment]
Why not? Are you working the .spec?

**Comment by sergiomb2** [comment]
https://github.com/RussianFedora/gnome-mpv
@paulcarroty  RussianFedora on github is other good example, how I'd link have the things

**Comment by paulcarroty** [comment]
@kuboosoft @sergiomb2 ok, I will to add to new source repository.
