### ISSUE TITLE
Make a new tree for each package

### ISSUE THREAD

**Issue by kuboosoft** [FedoraUnited/packages#4]
Hi, why not make a tree for each package?; I made a simple script; maybe can help us... My machine is a disasters I have much files :+1:

I will make the changes now, and upload src.rpm

**Comment by sergiomb2** [comment]
I also try to convince paul carroty to do that , but ...

**Comment by kuboosoft** [comment]
@sergiomb2 really? I'm not a expert using github; but how to we make a repository with the "organization" in terminal? It could make things easier. I made a simple script; It creates a repository, sort and put files in the correct way; isn't perfect but we can improve it. Remember if we use binary file here the limit is 2gb free approximate

**Comment by kuboosoft** [comment]
@sergiomb2 really? I'm not a expert using github; but how to we make a repository with the "organization" in terminal? It could make things easier. I made a simple script; It creates a repository, sort files and puts files in the correct way; isn't perfect but we can improve it. Remember if we use binary file here the limit is 1gb free approximate for each repository. I will test with my user, and fork using FedoraUnited"

**Comment by sergiomb2** [comment]
yes, we can script in terminal to create repos in github . 
you need create a token a after is just use the token: 
```
curl -H "Authorization: token 3eac29841b4e385252a8fa97349bbb10609b828" https://api.github.com/orgs/FedoraUnited/repos -d '{"name":"a52dec", "description":"A free ATSC A/52 stream decode"}'
git remote add origin git@github.com:FedoraUnited/a52dec.git
git checkout master
git checkout .
git push -u origin master
git checkout f20
git push -u origin f20
git checkout el6
git push -u origin el6

```

**Comment by sergiomb2** [comment]
# create github repos from a list
https://github.com/rpmfusion-infra/rpmfusion-tools/blob/master/create2github

**Comment by kuboosoft** [comment]
@sergiomb2 Here a different script, thanks for the line (https://api.github.com/orgs/FedoraUnited/repos); beatiful script...
[make_tree3.zip](https://github.com/FedoraUnited/packages/files/233252/make_tree3.zip)

**Comment by sergiomb2** [comment]
looks good, you may create whatever you want , be my guess :-)

**Comment by kuboosoft** [comment]
yes; also makes a description; puts the name, and the url; I will upload now; my internet is not congested now. I need to take advantage :)

**Comment by paulcarroty** [comment]
@kuboosoft, great work! So, if we now have specs and patches in every package repo - maybe time to delete it from `packages` repository?

What about `*src.rpm`? I think we still store it in `packages` repo.

@sergiomb2 

P.S. I has push the latest SRPMS to the `packages` repo.

**Comment by kuboosoft** [comment]
@paulcarroty why not upload also the src.rpm in each repository?; each repository gives 1GB free; if we only use the repository 'packages' is very poor. and we will need buy more space.  Why delete "packages" repository, only we need change the name; maybe a spec-devel and delete here all src.rpm

**Comment by paulcarroty** [comment]
@kuboosoft I know about limitation, this it's not a problem because we can delete the previous commits. The `packages` repo is good for TODO, discussion and multi-packages-related bugs. All SRPMS in one repo is very good for mass rebuilds.
