### ISSUE TITLE
Vlc: problem with codecs

### ISSUE THREAD

**Issue by paulcarroty** [FedoraUnited/packages#5]
$[SUBJ](https://plus.google.com/104617077706179713070/posts/hSiYxFAZAaX).

This is the problem with latest update? @sergiomb2 @kuboosoft ?

So, I'm try to build `mpv`; it's better and we need a reserve video player.

**Comment by alunux** [comment]
I have a problem with VLC too.

`VLC media player 2.2.2 Weatherwax (revision 2.2.2-0-g6259d80)`
`[000055b7ad0c2168] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.`
`"sni-qt/25976" WARN  23:56:15.883 void StatusNotifierItemFactory::connectToSnw() Invalid interface to SNW_SERVICE `
`[ass] Shaper: FriBidi 0.19.7 (SIMPLE) HarfBuzz-ng 1.2.6 (COMPLEX)`
`[ass] Using font provider fontconfig`
`[00007f790cc0e978] gstdecode decoder error: Error from appsrc0: Internal data flow error.`

**Comment by paulcarroty** [comment]
@alunux thx for report. Can you also try to play video with vlc 3.0? [packages](https://21d83acfa47e6d88f3937b3565370df8445dfc9e.googledrive.com/host/0ByOofIMiUfxPSG00M3hVRHVmYUE/vlc-3.0/).

**Comment by sergiomb2** [comment]
yeah , waiting for the fix

**Comment by kuboosoft** [comment]
Can any here rebuild the 'src.rpm'; with the current ffmpeg published here and test?

**Comment by paulcarroty** [comment]
@kuboosoft I can't build your package in copr:

```
checking a52dec/a52.h usability... no
checking a52dec/a52.h presence... no
checking for a52dec/a52.h... no
configure: error: Could not find liba52 on your system: you may get it from http://liba52.sf.net/. Alternatively you can use --disable-a52 to disable the a52 plugin.
RPM build errors:
error: Bad exit status from /var/tmp/rpm-tmp.KpWDQr (%build)
    Bad exit status from /var/tmp/rpm-tmp.KpWDQr (%build)
Child return code was: 1
```

**Comment by kuboosoft** [comment]
@paulcarroty please read the .spec... you need enable all codecs.
`mock -r fedora-YOUR_RELEASE-x86_64 --with=codecs vlc-3.0.0-1.20160229git10f9493.fc24.src.rpm`

vlc 3.0 works fine :)

**Comment by paulcarroty** [comment]
@kuboosoft 

```
configure: WARNING: unrecognized options: --enable-gnomevfs, --enable-vcdx
libvlc configuration
--------------------
version               : 3.0.0-git
system                : linux
architecture          : x86_64 mmx sse sse2
optimizations         : no
vlc aliases           : cvlc rvlc qvlc svlc nvlc
To build vlc and its plugins, type `make', or `./compile' if you like nice colors.
+ --enable-libmpeg2 --enable-mad --enable-avcodec --enable-avformat --enable-swscale --enable-postproc --enable-faad --enable-a52 --enable-dca --enable-twolame --enable-live555
/var/tmp/rpm-tmp.lHXabY: line 90: --enable-libmpeg2: command not found
```

**Comment by paulcarroty** [comment]
@kuboosoft success, check packages here - https://github.com/FedoraUnited/vlc . Laptop is bad to build vlc, we need a server :)

@sergiomb2 pls add to repo.

**Comment by sergiomb2** [comment]
added .

**Comment by kuboosoft** [comment]
thanks!

**Comment by kuboosoft** [comment]
@sergiomb2 can help me?
 @paulcarroty updated the vlc repository, but my local repository now is out day; how i can updated my local repository with the changes of Paul?

**Comment by paulcarroty** [comment]
@kuboosoft `git pull`?

**Comment by kuboosoft** [comment]
@paulcarroty I have problems updating my local git repositories; I made a change; I didn't see your update, then stopped the git pull... yes already solved it ( uff reading various guides); but exist a simple way make a update previously, and next make a git pull; generally is my first time, working with a team in github.

**Comment by paulcarroty** [comment]
@kuboosoft great. The latest vlc build can play multimedia without issues?

**Comment by paulcarroty** [comment]
@kuboosoft 
![fu](https://cloud.githubusercontent.com/assets/1550705/14844406/da2b52f4-0c5f-11e6-8214-f75d72a487d3.png)
