### ISSUE TITLE
Mpv players added: need to testing

### ISSUE THREAD

**Issue by paulcarroty** [FedoraUnited/packages#6]
I've add the mpv player (rpm and srpm) to repository: https://github.com/FedoraUnited/mpv

Need testing for F24; works in F25.

@sergiomb2 please add the binaries to your cloud repo.

It also can be a temporary fix for vlc problems, @alunux.

**Comment by sergiomb2** [comment]
I hope that is  a copy of https://github.com/rpmfusion/mpv ? 
I didn't understood this sentence " It also can be a temporary fix for vlc problems, @alunux."

**Comment by paulcarroty** [comment]
@sergiomb2, this is fixed package from Russian Fedora: https://github.com/FedoraUnited/mpv/issues/1

Sentence says "if we doesn't have any working player, time to try mpv".

**Comment by kuboosoft** [comment]
Totem plays correctly all formats, test it ;)

**Comment by paulcarroty** [comment]
Rebuild, all works. @sergiomb2 , pls add to repo: https://github.com/FedoraUnited/mpv

**Comment by sergiomb2** [comment]
published in 5 minutes
