### ISSUE TITLE
We need a mirror, Google Cloud is bad as repository

### ISSUE THREAD

**Issue by paulcarroty** [FedoraUnited/packages#7]
![](http://i.imgur.com/BWpCNl0.png)

For some users our Google Cloud doesn't working as expected, many users have a problem with adding our repository.

Accordingly, I suggest to search a free and stable alternative without traffic limitation. Sourceforge is unacceptable. Bitbucket now have a 2 GB limit, and we'll can use one repo for release.

What you think @kuboosoft @sergiomb2 ?

**Comment by sergiomb2** [comment]
hi , I think in create a home page , and put there the .repo , but I'm busy until Thursday

**Comment by sergiomb2** [comment]
dnf config-manager --add-repo=http://fedoraunited.github.io/fedora-enjoy24.repo

works

**Comment by kuboosoft** [comment]
@sergiomb2 solved the problem with github url, now works. I uploaded all src.rpm in each repository (neater); if you have a lot of src.rpm, this script can help you. Only needs change your user and pass (github) and make a 
[make_tree4.zip](https://github.com/FedoraUnited/packages/files/235795/make_tree4.zip)
"$HOME/enjoy24/srpm/foo.src.rpm" directory; this will create a directory called "$HOME/FedoraUnited/foo_repositories/tree.." 

 Also will push your changes, example if you updated the .spec :)

**Comment by paulcarroty** [comment]
@sergiomb2 @kuboosoft problem is not only in `.repo` URL, problem in stability. What if some user/maintainer get the 503 error in building/installing process? Why every maintainer must wait while @sergiomb2 add his package? It's bureaucracy.

So, I'm begin test of bitbucket

**Comment by sergiomb2** [comment]
I never had one problem, if I not use cache hashes , I think the problem was give a link with cache hash, I remove my post from G+ to avoid confusions.
we need use https://googledrive.com/host/0ByOofIMiUfxPSG00M3hVRHVmYUE/srpm/repoview/
and not https://21d83acfa47e6d88f3937b3565370df8445dfc9e.googledrive.com/host/0ByOofIMiUfxPSG00M3hVRHVmYUE/srpm/repoview/

**Comment by paulcarroty** [comment]
@sergiomb2 In any case we need a automatic backup if one beautiful day Google will banned us.

P.S. Google is blocked in some countries.

**Comment by kuboosoft** [comment]
Mmm free? Imposible...

**Comment by paulcarroty** [comment]
@kuboosoft https://blog.bitbucket.org/2014/05/30/repository-size-limits/

**Comment by paulcarroty** [comment]
@kuboosoft we need to try it: https://about.gitlab.com/2015/04/08/gitlab-dot-com-storage-limit-raised-to-10gb-per-repo/

**Comment by sergiomb2** [comment]
google cloud is not working smooth ?  
if someone doesn't not have access to google also doesn't access to Fedora united in g+ so doesn't know us ! :-)

**Comment by paulcarroty** [comment]
@sergiomb2 I talk about your account :8ball: 

Mirror is now up #10
